# -*- coding: utf-8 -*-
"""GENERADORDEHORARIOS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QGB_HQTLzaj5ocdv_nMCumdHpDeBV5q-
"""

import pandas as pd
import itertools

dias = ["lu","ma","mi","ju","vi","sa"]
horas = list(range(8,20))
letras = ["A","B","C","D","E","F"]

# -----------------------------
# CONFIGURACION
# -----------------------------

n = int(input("Numero de cursos: "))

print("\nCONFIGURACION DE CRUCES")

MAX_TT = int(input("Horas de cruce teoria-teoria (max 4): "))
MAX_TP = int(input("Horas de cruce teoria-practica (max 2): "))

MAX_TT = min(MAX_TT,4)
MAX_TP = min(MAX_TP,2)

# -----------------------------
# INGRESO DE CURSOS
# -----------------------------

cursos = []

for i in range(n):

    print("\nCURSO",i+1)
    nombre = input("Nombre del curso: ")

    dias_teoria = int(input("Cuantos dias de teoria tiene: "))
    secciones = int(input("Numero de secciones: "))

    lista_secciones = []

    for s in range(secciones):

        letra = letras[s]
        print("\nSeccion",letra)

        teorias = []

        for t in range(dias_teoria):

            print("Teoria",t+1)

            d = input("Dia: ")
            i_h = int(input("Hora inicio: "))
            f_h = int(input("Hora fin: "))

            teorias.append((d,i_h,f_h))

        print("Practica")

        d = input("Dia practica: ")
        i_h = int(input("Hora inicio: "))
        f_h = int(input("Hora fin: "))

        practica = (d,i_h,f_h)

        lista_secciones.append({
            "curso":nombre,
            "sec":letra,
            "teorias":teorias,
            "practica":practica
        })

    cursos.append(lista_secciones)

# -----------------------------
# VALIDAR HORARIO
# -----------------------------

def validar(comb):

    horario = {h:{d:[] for d in dias} for h in horas}

    TT = 0
    TP = 0

    for sec in comb:

        for (d,i,f) in sec["teorias"]:
            for h in range(i,f):
                horario[h][d].append(("T",sec["curso"],sec["sec"]))

        (d,i,f) = sec["practica"]

        for h in range(i,f):
            horario[h][d].append(("P",sec["curso"],sec["sec"]))

    for h in horas:
        for d in dias:

            celda = horario[h][d]

            if len(celda) <= 1:
                continue

            tipos = [x[0] for x in celda]

            # practica-practica prohibido
            if tipos.count("P") > 1:
                return None

            if tipos.count("T") > 1:
                TT += 1

            if "T" in tipos and "P" in tipos:
                TP += 1

            if TT > MAX_TT or TP > MAX_TP:
                return None

    return horario

# -----------------------------
# GENERAR HORARIOS
# -----------------------------

horarios_validos = []
contador = 0

for comb in itertools.product(*cursos):

    h = validar(comb)

    if not h:
        continue

    contador += 1
    horarios_validos.append(h)

    print("\n====================")
    print("HORARIO",contador)
    print("====================")

    tabla = []

    for hr in horas:

        fila = []

        for d in dias:

            celda = h[hr][d]

            if celda:
                texto = " / ".join([f"{c}-{s}-{t}" for t,c,s in celda])
            else:
                texto = ""

            fila.append(texto)

        tabla.append(fila)

    df = pd.DataFrame(tabla,columns=dias)
    df.index = [f"{h}:00-{h+1}:00" for h in horas]

    print(df)

print("\nTOTAL HORARIOS VALIDOS:",contador)

# -----------------------------
# EXPORTAR A EXCEL
# -----------------------------

writer = pd.ExcelWriter("horarios_generados.xlsx")

for i,horario in enumerate(horarios_validos):

    tabla = []

    for hr in horas:

        fila = []

        for d in dias:

            celda = horario[hr][d]

            if celda:
                texto = " / ".join([f"{c}-{s}-{t}" for t,c,s in celda])
            else:
                texto = ""

            fila.append(texto)

        tabla.append(fila)

    df = pd.DataFrame(tabla,columns=dias)
    df.index = [f"{h}:00-{h+1}:00" for h in horas]

    df.to_excel(writer,sheet_name=f"Horario_{i+1}")

writer.close()

print("\nArchivo generado: horarios_generados.xlsx")

from google.colab import files
files.download("horarios_generados.xlsx")